<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::create('assets',function(Blueprint $t){$t->id();$t->string('name');$t->string('symbol',20)->unique();$t->string('type',20)->default('crypto');$t->string('icon')->nullable();$t->string('coingecko_id')->nullable()->index();$t->unsignedTinyInteger('decimals')->default(8);$t->boolean('is_active')->default(true);$t->timestamps();});
 Schema::create('networks',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->boolean('is_active')->default(true);$t->unsignedInteger('confirmations')->default(1);$t->timestamps();});
 Schema::create('asset_networks',function(Blueprint $t){$t->id();$t->foreignId('asset_id')->constrained()->cascadeOnDelete();$t->foreignId('network_id')->constrained()->cascadeOnDelete();$t->boolean('deposit_enabled')->default(false);$t->boolean('withdrawal_enabled')->default(false);$t->decimal('fee',24,12)->default(0);$t->unique(['asset_id','network_id']);});
 Schema::create('exchange_pairs',function(Blueprint $t){$t->id();$t->foreignId('base_asset_id')->constrained('assets');$t->foreignId('quote_asset_id')->constrained('assets');$t->boolean('is_active')->default(true);$t->unsignedInteger('spread_bps')->default(100);$t->decimal('min_amount',24,12)->default(0);$t->decimal('max_amount',24,12)->nullable();$t->unique(['base_asset_id','quote_asset_id']);$t->timestamps();});
 Schema::create('rate_quotes',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->uuid('user_id')->nullable()->index();$t->foreignId('base_asset_id')->constrained('assets');$t->foreignId('quote_asset_id')->constrained('assets');$t->decimal('amount_send',36,18);$t->decimal('rate',36,18);$t->decimal('gross_receive',36,18);$t->decimal('fee_amount',36,18);$t->decimal('net_receive',36,18);$t->timestamp('expires_at');$t->timestamps();});
 Schema::create('exchange_orders',function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->uuid('user_id')->index();$t->foreignId('quote_id')->nullable()->constrained('rate_quotes')->nullOnDelete();$t->foreignId('base_asset_id')->constrained('assets');$t->foreignId('quote_asset_id')->constrained('assets');$t->decimal('amount_send',36,18);$t->decimal('amount_receive',36,18);$t->decimal('rate',36,18);$t->decimal('fee_amount',36,18);$t->string('status',40)->index();$t->string('payment_method',80);$t->string('sender_reference')->nullable();$t->string('receiver_address');$t->timestamp('expires_at')->nullable();$t->text('failure_reason')->nullable();$t->timestamps();});
 Schema::create('order_events',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained('exchange_orders')->cascadeOnDelete();$t->string('status',40);$t->text('message')->nullable();$t->json('metadata')->nullable();$t->timestamps();});
 Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained('exchange_orders')->cascadeOnDelete();$t->string('provider',50);$t->string('provider_reference')->nullable()->unique();$t->string('status',40)->index();$t->decimal('amount',36,18)->nullable();$t->string('currency',20)->nullable();$t->json('payload')->nullable();$t->timestamps();});
 Schema::create('withdrawals',function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained('exchange_orders')->cascadeOnDelete();$t->string('network')->nullable();$t->string('address')->nullable();$t->string('tx_hash')->nullable()->index();$t->decimal('amount',36,18)->nullable();$t->string('status',40)->index();$t->timestamps();});
 } public function down(): void {foreach(['withdrawals','payments','order_events','exchange_orders','rate_quotes','exchange_pairs','asset_networks','networks','assets'] as $t) Schema::dropIfExists($t);} };
